### ISSUE TITLE
Incorrectly highlights all template tags instead of only the root element.

### ISSUE THREAD

**Issue by Kisem** [VasilVerdouw/vue-colors#3]
![image](https://github.com/user-attachments/assets/012e5189-bc33-4b45-b961-407d6a764ea9)

**Comment by VasilVerdouw** [comment]
Thanks for letting me know, will work on this. What do you think is expected behavior?

Something like this?
```
<template> HIGHLIGHT START
    <template>
    </template>

    <template>
    </template>
</template> HIGHLIGHT END
```

**Comment by kamatil-dev** [comment]
> Thanks for letting me know, will work on this. What do you think is expected behavior?
> 
> Something like this?
> ```
> <template> HIGHLIGHT START
>     <template>
>     </template>
> 
>     <template>
>     </template>
> </template> HIGHLIGHT END
> ```

Yes, or maybe a different opacity color for recursive templates 
green>darker>darker green

**Comment by Kisem** [comment]
> Thanks for letting me know, will work on this. What do you think is expected behavior?
> 
> Something like this?
> 
> ```
> <template> HIGHLIGHT START
>     <template>
>     </template>
> 
>     <template>
>     </template>
> </template> HIGHLIGHT END
> ```

Correct.
