### ISSUE TITLE
It does not work correctly if there is more than one template tag in the file

### ISSUE THREAD

**Issue by RoelGerritsen** [VasilVerdouw/vue-colors#7]
Hi Drew, weird that it doesn't work when more than one template tag is present. When I tested the extension I made sure it did work with any amount of template, script or styling tags.

**Comment by zmaten** [comment]
Anytime there is more than one nested `<template>` tag it seems the extension is looking only for the first closing tag.
![image](https://github.com/user-attachments/assets/06c3b088-f2a5-4676-8d0f-6e3af572ee14)

**Comment by VasilVerdouw** [comment]
Related to issue #3
